plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ghost.tesla.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ghost.tesla.mobile'
        minSdk 26
        targetSdk 35
        versionCode 5
        versionName '0.2.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
